### ISSUE TITLE
Tracking Facade usage

### ISSUE THREAD

**Issue by haf** [logary/logary#141]
https://github.com/logary/logary#using-logary-in-a-library
- [x] [kafunk?](https://github.com/jet/kafunk/pull/56)
- [x] [suave](https://github.com/SuaveIO/suave/pull/493)
- [ ] paket – a lot of string interpolation, will take a while
- [x] [mailgun](https://github.com/haf/mailgun/commit/6d07f6a7c739ae3cf156639fd025ce032a8b6b3d)
- [x] [hawk](https://github.com/logibit/Logibit.Hawk/pull/10)
- [x] recq
- [ ] ionide
- [ ] forge
- [ ] fsharp.configuration
- [ ] project scaffold
- [ ] fsreveal
- [x] FS3 (S3 client)
- [x] [Fakta](https://github.com/logibit/Fakta/pull/32) (Vault/Consul client)
- [ ] MBrace
- [ ] FsPickler
- [ ] [FsSql](https://github.com/mausch/FsSql/pull/35)
- [ ] Hopac
- [x] [Http.fs](https://github.com/haf/Http.fs/commit/466274a59a50a7fe7a65d6aba3999938ddcd805a)
- [ ] Fuchu
